name:                nihongo
version:             0.1.0
github:              "kavinvin/nihongo"
license:             BSD3
author:              "Kavin Ruengprateepsang  "
maintainer:          "kavinvin.vin@gmail.com"
copyright:           "2022 Kavin Ruengprateepsang"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kavinvin/nihongo#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  nihongo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nihongo

tests:
  nihongo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nihongo
